import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import tailwindcss from "@tailwindcss/vite";
import istanbul from "vite-plugin-istanbul";
import { defineConfig } from "wxt";

// Read version from package.json
const packageJson = JSON.parse(readFileSync(resolve(__dirname, "package.json"), "utf8"));
const version = packageJson.version;

// Check if we're running in coverage mode
const isCoverage = process.env.CI_COVERAGE === "true";

// Extract repo info from git remote
let repoUrl = "https://github.com/JesseKoldewijn/agnostic-devkit";
try {
	const remoteUrl = execSync("git remote get-url origin").toString().trim();
	if (remoteUrl.includes("github.com")) {
		const match = remoteUrl.match(/github\.com[:/]([^/]+\/[^/.]+)(\.git)?$/);
		if (match?.[1]) {
			repoUrl = `https://github.com/${match[1]}`;
		}
	}
} catch {
	// Fallback to default if git fails (e.g. in some CI environments)
}

export default defineConfig({
	outDir: "build-output",
	webExt: {
		disabled: true,
	},
	imports: {
		addons: [],
	},
	manifest: async (env) => {
		const isProduction = env.mode === "production";
		const browserTarget = env.browser;
		const isFirefox = browserTarget === "firefox";

		const extensionEnv = process.env.EXTENSION_ENV;
		let nameSuffix = "";
		if (extensionEnv === "canary") {
			nameSuffix = " (Canary)";
		} else if (extensionEnv === "development" || !isProduction) {
			nameSuffix = " (Development)";
		}

		const prettyBrowserTarget = browserTarget.charAt(0).toUpperCase() + browserTarget.slice(1);
		const name = `Agnostic Devkit for ${prettyBrowserTarget}${nameSuffix}`;

		const isDevIcon = extensionEnv === "development" || extensionEnv === "canary" || !isProduction;

		// Base permissions for all browsers
		const basePermissions = ["storage", "activeTab", "tabs", "notifications", "cookies"];

		// Chrome-specific permissions (MV3)
		const chromePermissions = [...basePermissions, "scripting", "sidePanel"];

		// Firefox permissions (MV2) - no scripting or sidePanel
		const firefoxPermissions = [...basePermissions];

		return {
			description: "A platform agnostic devkit for web development",
			host_permissions: ["*://*/*"],
			name,
			options_page: "settings.html",
			permissions: isFirefox ? firefoxPermissions : chromePermissions,
			// Only include side_panel for Chrome (Firefox uses sidebar_action auto-generated by WXT)
			...(isFirefox ? {} : { side_panel: { default_path: "sidepanel.html" } }),
			// Firefox requires browser_specific_settings with a gecko ID
			...(isFirefox
				? {
						browser_specific_settings: {
							gecko: {
								id: "agnostic-devkit@jessekoldewijn.dev",
							},
						},
					}
				: {}),
			web_accessible_resources: [
				{
					matches: ["<all_urls>"],
					resources: ["*"],
				},
			],
			icons: {
				16: isDevIcon ? "/icons/icon-16-red.png" : "/icons/icon-16.png",
				48: isDevIcon ? "/icons/icon-48-red.png" : "/icons/icon-48.png",
				128: isDevIcon ? "/icons/icon-128-red.png" : "/icons/icon-128.png",
			},
		};
	},
	modules: ["@wxt-dev/module-solid"],
	srcDir: "src",
	hooks: {
		"build:done": (wxt) => {
			const isWsl = process.env.WSL_DISTRO_NAME !== undefined;
			if (isWsl) {
				// Small delay to ensure it logs after the "Load ..." message
				setTimeout(() => {
					try {
						const winPath = execSync(`wslpath -w "${wxt.config.outDir}"`).toString().trim();
						wxt.logger.info(`Extension output (Windows): ${winPath}`);
						execSync(`echo -n "${winPath}" | clip.exe`);
						wxt.logger.success("Copied to Windows clipboard!");
					} catch {
						wxt.logger.warn("Failed to copy extension path to Windows clipboard.");
					}
				}, 100);
			}
		},
	},
	vite: () => ({
		server: {
			port: process.env.PORT ? parseInt(process.env.PORT, 10) : 3001,
			strictPort: true,
		},
		define: {
			__REPO_URL__: JSON.stringify(repoUrl),
			__EXTENSION_ENV__: JSON.stringify(process.env.EXTENSION_ENV || "development"),
			__EXTENSION_VERSION__: JSON.stringify(version),
		},
		build: {
			// Generate source maps for coverage
			sourcemap: isCoverage ? "inline" : false,
		},
		plugins: [
			tailwindcss(),
			// Add Istanbul instrumentation for E2E coverage
			...(isCoverage
				? [
						istanbul({
							exclude: ["node_modules", "src/test/**/*"],
							extension: [".ts", ".tsx"],
							forceBuildInstrument: true,
							include: "src/**/*",
							requireEnv: false,
						}),
					]
				: []),
		],
		resolve: {
			alias: {
				"@": resolve(__dirname, "./src"),
			},
		},
	}),
});
