// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
	export type PublicPath =
		| ""
		| "/"
		| "/assets/fonts/Geist-Black.woff2"
		| "/assets/fonts/Geist-Bold.woff2"
		| "/assets/fonts/Geist-Medium.woff2"
		| "/assets/fonts/Geist-Regular.woff2"
		| "/assets/fonts/Geist-SemiBold.woff2"
		| "/assets/fonts/GeistMono-Medium.woff2"
		| "/assets/fonts/GeistMono-Regular.woff2"
		| "/background.js"
		| "/content-scripts/content.js"
		| "/icons/README.md"
		| "/icons/icon-128-red.png"
		| "/icons/icon-128-red.svg"
		| "/icons/icon-128.png"
		| "/icons/icon-128.svg"
		| "/icons/icon-16-red.png"
		| "/icons/icon-16-red.svg"
		| "/icons/icon-16.png"
		| "/icons/icon-16.svg"
		| "/icons/icon-48-red.png"
		| "/icons/icon-48-red.svg"
		| "/icons/icon-48.png"
		| "/icons/icon-48.svg"
		| "/popup.html"
		| "/settings.html"
		| "/sidepanel.html";
	type HtmlPublicPath = Extract<PublicPath, `${string}.html`>;
	export interface WxtRuntime {
		getURL(path: PublicPath): string;
		getURL(path: `${HtmlPublicPath}${string}`): string;
	}
}
